# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

rachel = User.find_or_create_by(email: 'r@a.a')
amanda = User.find_or_create_by(email: 'a@a.a')

shirt = Category.create(name: "shirt", part_of_body: "torso")
jacket = Category.create(name: "jacket", part_of_body: "torso")
vest = Category.create(name: "vest", part_of_body: "torso")
tank = Category.create(name: "tank", part_of_body: "torso")
pants = Category.create(name: "pants", part_of_body: "legs")
shorts = Category.create(name: "shorts", part_of_body: "legs")
skirt = Category.create(name: "skirt", part_of_body: "legs")
leggings = Category.create(name: "leggings", part_of_body: "legs")
skort = Category.create(name: "skort", part_of_body: "legs")
shoes = Category.create(name: "shoes", part_of_body: "feet")

blue_jeans1 = ClothingItem.create(name: "Jeans", color: "blue", fanciness: 1, category: pants)
blue_jeans2 = ClothingItem.create(name: "Jeans", color: "blue", fanciness: 2, category: pants)
blue_jeans3 = ClothingItem.create(name: "Jeans", color: "blue", fanciness: 3, category: pants)
blue_jeans4 = ClothingItem.create(name: "Jeans", color: "blue", fanciness: 4, category: pants)
black_jeans = ClothingItem.create(name: "Jeans", color: "black", fanciness: 3, category: pants)
black_trousers = ClothingItem.create(name: "Trousers", color: "black", fanciness: 3, category: pants)
pink_cords = ClothingItem.create(name: "Cords", color: "pink", fanciness: 2, category: pants)
orange_cords = ClothingItem.create(name: "Cords", color: "orange", fanciness: 2, category: pants)
green_khakis = ClothingItem.create(name: "Khakis", color: "green", fanciness: 4, category: pants)
brown_khakis =  ClothingItem.create(name: "Khakis", color: "brown", fanciness: 4, category: pants)
white_polo =  ClothingItem.create(name: "Polo", color: "white", fanciness: 3, category: shirt)
blue_polo =  ClothingItem.create(name: "Polo", color: "blue", fanciness: 2, category: shirt)
white_blouse =  ClothingItem.create(name: "Blouse", color: "white", fanciness: 4, category: shirt)
purple_blouse = ClothingItem.create(name: "Blouse", color: "purple", fanciness: 3, category: shirt)
flower_blouse = ClothingItem.create(name: "Blouse", color: "flower print", fanciness: 4, category: shirt)
blue_t = ClothingItem.create(name: "T-shirt", color: "blue", fanciness: 2, category: shirt)
green_t = ClothingItem.create(name: "T-shirt", color: "green", fanciness: 2, category: shirt)
blue_graphic_t = ClothingItem.create(name: "T-shirt", color: "blue with graphics", fanciness: 2, category: shirt)
red_t = ClothingItem.create(name: "T-shirt", color: "red", fanciness: 2, category: shirt)
yellow_t = ClothingItem.create(name: "T-shirt", color: "yellow", fanciness: 2, category: shirt)
black_t = ClothingItem.create(name: "T-shirt", color: "black", fanciness: 2, category: shirt)
blue_sneakers =  ClothingItem.create(name: "Sneakers", color: "blue multi", fanciness: 1, category: shoes)
black_loafers =  ClothingItem.create(name: "Loafers", color: "black", fanciness: 4, category: shoes)
brown_brogues =  ClothingItem.create(name: "Brogues", color: "brown", fanciness: 5, category: shoes)
gold_sandals =  ClothingItem.create(name: "Sandals", color: "gold", fanciness: 2, category: shoes)
nude_pumps =  ClothingItem.create(name: "Pumps", color: "nude", fanciness: 2, category: shoes)

rachel.clothing_items = [blue_jeans3, blue_jeans4, black_trousers, orange_cords, white_polo, white_blouse, blue_t, green_t, red_t, black_t, blue_sneakers, brown_brogues, gold_sandals, nude_pumps]
amanda.clothing_items = [blue_jeans3, blue_jeans4, black_trousers, orange_cords, white_polo, white_blouse, blue_t, green_t, red_t, black_t, blue_sneakers, brown_brogues, gold_sandals, nude_pumps, pink_cords, purple_blouse, yellow_t]

amanda.outfits.create(name: "Interview outfit", clothing_item_ids: [nude_pumps.id, white_blouse.id, black_trousers.id])
rachel.outfits.create(name: "Night on the town", clothing_item_ids: [gold_sandals.id, white_blouse.id, black_trousers.id])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
rachel.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
amanda.outfits.create(clothing_item_ids: [rand(1..9), rand(10..20), rand(21..25)])
